version: '3.8'

services:
  php-fpm:
    build: .
    container_name: php-fpm
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
